import { Content } from '../types';

export const content: Record<'en' | 'gr', Content> = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      portfolio: "Portfolio",
      contact: "Contact",
    },
    home: {
      name: "Peter Lamb",
      title: "Software & AI Engineering Consultant",
      subtitle: "Helping businesses design, build, and scale reliable software and data solutions.",
      specialties: "Specialized in Python, AI/ML, SaaS, and big data.",
      cta: "Work with me",
      servicesTitle: "Services snapshot",
      services: [
        { title: "Software Engineering", description: "Scalable back-end systems, APIs, SaaS platforms." },
        { title: "AI & Machine Learning", description: "NLP, model development, and MLOps practices." },
        { title: "Big Data & Analytics", description: "Data pipelines, Spark, cloud-based processing." },
        { title: "Consulting & Support", description: "Technical strategy, feasibility studies, and audits." },
      ],
      credibility: "Trusted by companies in AI, SaaS, and cybersecurity, including Workable, NannyML, and Orfium.",
    },
    about: {
      title: "About Me",
      greeting: "Hi, I’m Peter Lamb (Petros Lambropoulos)",
      intro: "a senior software engineer based in Athens, Greece and Canada. I have over 10 years of experience working in AI, SaaS, and security analytics, with a strong background in:",
      experienceTitle: "Experience",
      experience: [
        "Python & backend systems",
        "Machine learning & natural language processing",
        "Big data engineering & distributed systems",
        "Software product development",
      ],
      skillsTitle: "Technical Skills",
      skills: [
        { title: "Languages", items: ["Python", "SQL", "JavaScript/TypeScript", "Bash"] },
        { title: "Frameworks & Libraries", items: ["Django", "Flask", "FastAPI", "React", "PySpark", "Scikit-learn", "Pandas", "LangChain"] },
        { title: "Tools & Platforms", items: ["Docker", "Kubernetes", "Elasticsearch", "PostgreSQL", "Git", "Jenkins", "Nginx"] },
        { title: "Cloud & MLOps", items: ["AWS (EC2, S3, RDS)", "Google Cloud", "Terraform", "MLflow", "Airflow"] },
      ],
      educationTitle: "Education",
      education: [
        "MSc in Computer Science (University of Edinburgh)",
        "MSc in Electronic Automation & Information Systems (University of Athens)",
      ],
      languagesTitle: "Languages",
      languages: "English (professional), Greek (native), German (limited working).",
      resumeButton: "Download Resume",
    },
    services: {
      title: "Services",
      intro: "I offer flexible consulting and development services, tailored to your needs:",
      categories: [
        { title: "Software Engineering", items: ["Python development (Flask, Django, FastAPI).", "SaaS platforms and APIs.", "System architecture & integration."] },
        { title: "AI & Machine Learning", items: ["Natural language processing (text classification, search, embeddings).", "Generative AI exploration (OpenAI, LangChain, Pinecone).", "MLOps & production model deployment."] },
        { title: "Big Data & Analytics", items: ["Data pipeline design (Spark, Elasticsearch, AWS).", "Large-scale log parsing and analytics.", "Forecasting & time-series modeling."] },
        { title: "Consulting & Technical Support", items: ["Feasibility analysis and PoCs.", "Requirements gathering & architecture design.", "Ongoing support for specialized applications."] },
      ],
    },
    portfolio: {
      title: "Portfolio",
      intro: "Selected work and case studies:",
      projects: [
        { title: "Dance School Management SaaS", description: "Full-stack development of a scheduling and billing tool for performing arts schools." },
        { title: "Alzheimer’s Text Classification", description: "NLP prototype for early diagnosis support." },
        { title: "Taxi Demand Forecasting", description: "Predictive model using time-series analysis." },
        { title: "Flask ML Server", description: "Lightweight server for TensorFlow model deployment." },
        { title: "Cybersecurity Platforms", description: "Data analytics for large-scale intrusion detection (enterprise clients)." },
      ],
      githubCta: "See more on GitHub",
    },
    contact: {
      title: "Contact",
      intro: "Let’s talk about your project.",
      detailsTitle: "Contact Details",
      email: "Email",
      linkedin: "LinkedIn",
      github: "GitHub",
      formIntro: "Or send a message directly through the form below.",
      formName: "Your Name",
      formEmail: "Your Email",
      formMessage: "Your Message",
      formSubmit: "Send Message",
    },
    footer: {
      copyright: "© 2025 Peter Lamb. All rights reserved.",
      availability: "Available for international consulting & freelance projects.",
    },
    announcements: {
      languageChanged: "Language set to English",
    },
    ariaLabels: {
      mainNav: "Main navigation",
      socialNav: "Social media links",
      switchToEnglish: "Switch to English",
      switchToGreek: "Switch to Greek",
    }
  },
  gr: {
    nav: {
      home: "Αρχική",
      about: "Σχετικά",
      services: "Υπηρεσίες",
      portfolio: "Portfolio",
      contact: "Επικοινωνία",
    },
    home: {
      name: "Peter Lamb",
      title: "Σύμβουλος Λογισμικού & Τεχνητής Νοημοσύνης",
      subtitle: "Βοηθώ επιχειρήσεις να σχεδιάσουν, να αναπτύξουν και να επεκτείνουν αξιόπιστες λύσεις λογισμικού και δεδομένων.",
      specialties: "Εξειδίκευση σε Python, AI/ML, SaaS και Big Data.",
      cta: "Συνεργαστείτε μαζί μου",
      servicesTitle: "Υπηρεσίες με μια ματιά",
      services: [
        { title: "Μηχανική Λογισμικού", description: "Κλιμακούμενα back-end συστήματα, APIs, SaaS πλατφόρμες." },
        { title: "Τεχνητή Νοημοσύνη & Μηχανική Μάθηση", description: "NLP, ανάπτυξη μοντέλων, MLOps πρακτικές." },
        { title: "Big Data & Αναλύσεις", description: "Pipelines δεδομένων, Spark, cloud-based επεξεργασία." },
        { title: "Συμβουλευτική & Υποστήριξη", description: "Στρατηγική τεχνολογίας, μελέτες σκοπιμότητας, audits." },
      ],
      credibility: "Εμπιστεύτηκαν τις υπηρεσίες μου εταιρείες AI, SaaS και κυβερνοασφάλειας, όπως οι Workable, NannyML και Orfium.",
    },
    about: {
      title: "Σχετικά με εμένα",
      greeting: "Γεια σας, είμαι ο Peter Lamb (Πέτρος Λαμπρόπουλος)",
      intro: "senior software engineer με έδρα την Αθήνα και τον Καναδά. Διαθέτω πάνω από 10 χρόνια εμπειρίας στην AI, SaaS και στην ανάλυση ασφάλειας, με ισχυρό υπόβαθρο σε:",
      experienceTitle: "Εμπειρία",
      experience: [
        "Python & back-end συστήματα",
        "Machine learning & επεξεργασία φυσικής γλώσσας (NLP)",
        "Big Data & κατανεμημένα συστήματα",
        "Ανάπτυξη προϊόντων λογισμικού",
      ],
      skillsTitle: "Τεχνικές Δεξιότητες",
      skills: [
        { title: "Γλώσσες Προγραμματισμού", items: ["Python", "SQL", "JavaScript/TypeScript", "Bash"] },
        { title: "Frameworks & Βιβλιοθήκες", items: ["Django", "Flask", "FastAPI", "React", "PySpark", "Scikit-learn", "Pandas", "LangChain"] },
        { title: "Εργαλεία & Πλατφόρμες", items: ["Docker", "Kubernetes", "Elasticsearch", "PostgreSQL", "Git", "Jenkins", "Nginx"] },
        { title: "Cloud & MLOps", items: ["AWS (EC2, S3, RDS)", "Google Cloud", "Terraform", "MLflow", "Airflow"] },
      ],
      educationTitle: "Σπουδές",
      education: [
        "MSc Computer Science (University of Edinburgh)",
        "MSc Ηλεκτρονικός Αυτοματισμός & Πληροφοριακά Συστήματα (ΕΚΠΑ)",
      ],
      languagesTitle: "Γλώσσες",
      languages: "Αγγλικά (επαγγελματικά), Ελληνικά (μητρική), Γερμανικά (βασικά επαγγελματικά).",
      resumeButton: "Λήψη Βιογραφικού",
    },
    services: {
      title: "Υπηρεσίες",
      intro: "Προσφέρω ευέλικτες συμβουλευτικές και αναπτυξιακές υπηρεσίες, προσαρμοσμένες στις ανάγκες σας:",
      categories: [
        { title: "Μηχανική Λογισμικού", items: ["Python development (Flask, Django, FastAPI).", "SaaS πλατφόρμες και APIs.", "Σχεδιασμός & ενοποίηση συστημάτων."] },
        { title: "Τεχνητή Νοημοσύνη & Μηχανική Μάθηση", items: ["Επεξεργασία φυσικής γλώσσας (ταξινόμηση κειμένων, αναζήτηση, embeddings).", "Generative AI (OpenAI, LangChain, Pinecone).", "MLOps & παραγωγική διάθεση μοντέλων."] },
        { title: "Big Data & Αναλύσεις", items: ["Σχεδιασμός pipelines δεδομένων (Spark, Elasticsearch, AWS).", "Ανάλυση και επεξεργασία μεγάλων logs.", "Πρόβλεψη & μοντέλα χρονοσειρών."] },
        { title: "Συμβουλευτική & Τεχνική Υποστήριξη", items: ["Μελέτες σκοπιμότητας & PoCs.", "Ανάλυση απαιτήσεων & αρχιτεκτονικός σχεδιασμός.", "Συνεχής υποστήριξη σε εξειδικευμένες εφαρμογές."] },
      ],
    },
    portfolio: {
      title: "Portfolio",
      intro: "Επιλεγμένα έργα και case studies:",
      projects: [
        { title: "Dance School Management SaaS", description: "Full-stack ανάπτυξη εργαλείου προγραμματισμού και χρεώσεων για σχολές παραστατικών τεχνών." },
        { title: "Alzheimer’s Text Classification", description: "NLP πρωτότυπο για υποστήριξη πρώιμης διάγνωσης." },
        { title: "Taxi Demand Forecasting", description: "Προγνωστικό μοντέλο με χρήση ανάλυσης χρονοσειρών." },
        { title: "Flask ML Server", description: "Lightweight server για deployment μοντέλων TensorFlow." },
        { title: "Cybersecurity Platforms", description: "Ανάλυση δεδομένων για ανίχνευση εισβολών μεγάλης κλίμακας (enterprise clients)." },
      ],
      githubCta: "Δείτε περισσότερα στο GitHub",
    },
    contact: {
      title: "Επικοινωνία",
      intro: "Ας συζητήσουμε για το έργο σας.",
      detailsTitle: "Στοιχεία Επικοινωνίας",
      email: "Email",
      linkedin: "LinkedIn",
      github: "GitHub",
      formIntro: "Ή στείλτε μήνυμα μέσω της φόρμας επικοινωνίας.",
      formName: "Το Όνομά σας",
      formEmail: "Το Email σας",
      formMessage: "Το Μήνυμά σας",
      formSubmit: "Αποστολή Μηνύματος",
    },
    footer: {
      copyright: "© 2025 Peter Lamb. Με την επιφύλαξη παντός δικαιώματος.",
      availability: "Διαθέσιμος για διεθνή projects και συμβουλευτικές συνεργασίες.",
    },
    announcements: {
      languageChanged: "Η γλώσσα άλλαξε σε Ελληνικά",
    },
    ariaLabels: {
      mainNav: "Κύρια πλοήγηση",
      socialNav: "Σύνδεσμοι κοινωνικών δικτύων",
      switchToEnglish: "Αλλαγή στα Αγγλικά",
      switchToGreek: "Αλλαγή στα Ελληνικά",
    },
  },
};